defmodule ExGoCDWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :ex_gocd

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_ex_gocd_key",
    signing_salt: "zzyvy3it",
    same_site: "Lax"
  ]

  socket "/socket", ExGoCDWeb.UserSocket, websocket: true

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # GoCD agent protocol: WebSocket at /agent-websocket with action/data JSON (see docs/rewrite.md).
  # Serializer must be a list of {module, vsn} so Phoenix.negotiate_serializer/2 matches client vsn (e.g. "1.0.0").
  socket "/agent-websocket", ExGoCDWeb.AgentSocket,
    websocket: [
      serializer: [{ExGoCDWeb.AgentSerializer, "1.0.0"}],
      connect_info: [:peer_data]
    ]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :ex_gocd,
    gzip: not code_reloading?,
    only: ExGoCDWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :ex_gocd
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug ExGoCDWeb.Router
end
