[SERVICE]
    Flush         2
    Log_Level     info

[INPUT]
    Name          tail
    Path          /host-logs/ex_gocd_agent*.log
    Tag           exgocd.agent
    Parser        json

[INPUT]
    Name          tail
    Path          /host-logs/ex_gocd_server*.log
    Tag           exgocd.server
    Parser        json

[OUTPUT]
    Name          loki
    Match         exgocd.*
    host          loki
    port          3100
    labels        job=fluentbit,app=ex_gocd,source=$tag
    label_keys    $tag
