apiVersion: 1

datasources:
  - name: Loki
    type: loki
    uid: loki
    url: http://loki:3100
    access: proxy
    editable: true
    isDefault: true
    jsonData:
      derivedFields:
        - name: traceID
          matcherRegex: '"trace_id":"(\w+)"'
          url: '$${__value.raw}'
          datasourceUid: jaeger
          urlDisplayLabel: 'Jaeger trace'
