import Config

# Disable spec caching in dev so changes are picked up immediately
config :open_api_spex, :cache_adapter, OpenApiSpex.Plug.NoneCache

# Configure your database
config :ex_gocd, ExGoCD.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "ex_gocd_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: String.to_integer(System.get_env("POOL_SIZE") || "10")

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :ex_gocd, ExGoCDWeb.Endpoint,
  # URL used when building links (e.g. console log upload URL for agents)
  url: [host: "localhost", port: 4000],
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "Prdu+ZZ5W0wm41lvF4MgIHGsUb8f8ipnuPM7FZby/fB6BJePv/aegKeKP0XU4rcW",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:ex_gocd, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:ex_gocd, ~w(--watch)]}
  ]

# ## SSL Support

# Mailer: SMTP → smtp4dev (docker compose up -d smtp4dev)
# Web UI: http://localhost:8025
config :ex_gocd, ExGoCD.Mailer,
  adapter: Swoosh.Adapters.SMTP,
  relay: "localhost",
  port: 2525,
  auth: :always,
  username: "",
  password: "",
  ssl: false,
  tls: :never,
  retries: 1

#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :ex_gocd, ExGoCDWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Gettext translations
      ~r"priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/ex_gocd_web/router\.ex$"E,
      ~r"lib/ex_gocd_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# In mock data mode (USE_MOCK_DATA=true), suppress polling and use MockImpl
if System.get_env("USE_MOCK_DATA") == "true" do
  config :ex_gocd,
    poller_interval: :none,
    enable_timer_scheduler: false,
    scm_client: ExGoCD.Materials.ScmClient.MockImpl,
    git_client: ExGoCD.Materials.GitClient.MockImpl
end

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# ── OpenTelemetry → Collector → Jaeger (dev only) ──────────────────────
# Instrumentation (Phoenix + Ecto) attached by ExGoCD.Otel.setup/0.
# Spans flow: ex_gocd → OTLP HTTP (localhost:4318) → Collector → Jaeger
# Collector and Jaeger started via: docker compose up -d jaeger otel-collector
# Jaeger UI: http://localhost:16686/search
config :ex_gocd, :otel,
  exporter: :otlp,
  otlp_endpoint: "http://localhost:4318",
  service_name: "ex_gocd"

config :opentelemetry,
  traces_exporter: {:opentelemetry_exporter, %{}},
  resource: %{service: %{name: "ex_gocd"}}

config :opentelemetry_exporter,
  otlp_endpoint: "http://localhost:4318"

# ── JSON log file for Fluent Bit → Loki (dev only) ──────────────────────
# Console logging continues as normal. A JSON file sidecar is written for
# Fluent Bit to tail and forward to Loki for Grafana log dashboards.
# The backend is attached in Application.start/2 (no :backends config needed).
# See: fluentbit/fluent-bit.conf, lib/ex_gocd/logger_json.ex
config :logger, ExGoCD.LoggerJSON,
  path: "/tmp/ex_gocd_server.log",
  level: :info

# ── Plugin configuration (dev) ─────────────────────────────────────────
# Set EX_GOCD_PLUGINS to a comma-separated list to load example plugins:
#   EX_GOCD_PLUGINS=regional_affinity,corp_policy
#
# In cluster mode (process-compose.cluster.yaml), EX_GOCD_CLUSTER=1
# enables the default plugin set.
if System.get_env("EX_GOCD_CLUSTER") == "1" do
  config :ex_gocd, :plugins,
    agent_selector: ExGoCD.Plugin.Managed.RegionalAffinity,
    org_hierarchy: ExGoCD.Plugin.Managed.SimpleOrgChart
else
  plugin_list =
    System.get_env("EX_GOCD_PLUGINS", "")
    |> String.split(",", trim: true)
    |> Enum.map(&String.trim/1)

  plugins =
    if "regional_affinity" in plugin_list,
      do: [agent_selector: ExGoCD.Plugin.Managed.RegionalAffinity],
      else: []

  plugins =
    if "corp_policy" in plugin_list,
      do: Keyword.put(plugins, :agent_selector, ExGoCD.Plugin.Managed.CorpPolicy),
      else: plugins

  plugins =
    if "org_chart" in plugin_list,
      do: Keyword.put(plugins, :org_hierarchy, ExGoCD.Plugin.Managed.SimpleOrgChart),
      else: plugins

  config :ex_gocd, :plugins, plugins
end
