import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :ex_gocd, ExGoCDWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# SSL termination is handled at the reverse proxy / load-balancer layer.
# Do NOT set force_ssl here — the same Docker image is used for E2E tests
# over plain HTTP. If you need HSTS or SSL redirection, configure it in
# your proxy (nginx, Caddy, ALB, etc.).

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
